// <auto-generated />
namespace Weather_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class weatherdbeasier2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(weatherdbeasier2));
        
        string IMigrationMetadata.Id
        {
            get { return "202304190232051_weather-db-easier2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
